// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrclUBMSkDI0KJH5KDKtPWqPBbEbLue0s',
    appId: '1:313392960737:web:a967faa53c3c72e4df53a0',
    messagingSenderId: '313392960737',
    projectId: 'ecomly-flutter',
    authDomain: 'ecomly-flutter.firebaseapp.com',
    storageBucket: 'ecomly-flutter.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUQv5OWlesnO7oZYmq0yRtE1cBiQIE8xc',
    appId: '1:313392960737:android:c1213ab35d26789ddf53a0',
    messagingSenderId: '313392960737',
    projectId: 'ecomly-flutter',
    storageBucket: 'ecomly-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSjUktz3RbbtcrKdqDgW0J5vG5OAdJVk8',
    appId: '1:313392960737:ios:cbfd38ce8447e07bdf53a0',
    messagingSenderId: '313392960737',
    projectId: 'ecomly-flutter',
    storageBucket: 'ecomly-flutter.appspot.com',
    iosBundleId: 'com.ecomly.food.ecomlyFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCSjUktz3RbbtcrKdqDgW0J5vG5OAdJVk8',
    appId: '1:313392960737:ios:172ed08b103be5eddf53a0',
    messagingSenderId: '313392960737',
    projectId: 'ecomly-flutter',
    storageBucket: 'ecomly-flutter.appspot.com',
    iosBundleId: 'com.ecomly.food.ecomlyFlutter.RunnerTests',
  );
}
